### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sam-ulrich1** [TheYkk/db-generate#1]
Hey man,

I forked your repo only to realize it technically doesn't have a license. The main repo does so I imagine that you're cool with adding one but would you mind? Makes the whole legal side a bit clearer

**Comment by TheYkk** [comment]
Hey, sorry for that. Let me add MIT license.

**Comment by sam-ulrich1** [comment]
@TheYkk If you're curious check out my fork.
https://github.com/Gage-Technologies/pwned-passcheck-generate
